# Generated by Django 5.1.2 on 2024-12-08 09:27

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('searchName', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=1000)),
                ('postLinks', models.JSONField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appService.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('discription', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/images/posts')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('foodDiscription', models.TextField(blank=True, max_length=500, null=True)),
                ('diseaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appService.diseases')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/medicines/')),
                ('PrescriptionsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='appService.prescriptions')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appService.categories')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appService.post')),
            ],
            options={
                'unique_together': {('postId', 'categoryId')},
            },
        ),
    ]
