# Generated by Django 5.1.2 on 2024-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_diseases_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/medicines/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/posts'),
        ),
    ]
