# Generated by Django 5.1.2 on 2024-12-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlService', '0002_medicines_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='vector',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
